### ISSUE TITLE
Error: TypeError: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by leigh-johnson** [asyncapi/vs-asyncapi-preview#146]
#### Describe the bug
:wave: Hey there, thanks for all the hard work on this extension! I'm seeing the following error when I attempt to open a preview using command+shift+p.

```
2022-11-27 09:56:40.704 [error] TypeError: The "path" argument must be of type string. Received undefined
	at new NodeError (node:internal/errors:371:5)
	at validateString (node:internal/validators:120:11)
	at Object.dirname (node:path:1276:5)
	at a (/home/leigh/.vscode/extensions/asyncapi.asyncapi-preview-0.4.0/dist/extension.js:1:179602)
	at /home/leigh/.vscode/extensions/asyncapi.asyncapi-preview-0.4.0/dist/extension.js:1:181584
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async s._executeContributedCommand (/snap/code/113/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:92:111367) asyncapi.preview {"value":"asyncapi.asyncapi-preview","_lower":"asyncapi.asyncapi-preview"}
```
VS Code version:
```
Version: 1.73.1
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-09T03:54:53.913Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.15.0-53-generic snap
Sandboxed: No
```

#### How to Reproduce

1. Open an async API schema
2. Press control+shift+p or command+shift-p to open commands
3. Select `Preview AsyncAPI` command
4. I'm getting prompted to open an AsyncAPI file, even though I already have one open in VS Code. I verified my schema is valid via https://studio.asyncapi.com/
![Screenshot from 2022-11-27 10-00-28](https://user-images.githubusercontent.com/2601819/204152078-efe74fd0-405e-41ef-845a-7316a7c178fb.png)

5. After selecting the Async API schema again (even though it's already open in my editor), I'm seeing the following error:
![Screenshot from 2022-11-27 10-03-28](https://user-images.githubusercontent.com/2601819/204152124-b0565da2-2586-4c4a-a3ac-564d88d8ee4a.png)

In VSCode's `Output` under `Log (Extension Host)` I see the following error:
```
2022-11-27 10:05:00.129 [error] TypeError: The "path" argument must be of type string. Received undefined
	at new NodeError (node:internal/errors:371:5)
	at validateString (node:internal/validators:120:11)
	at Object.dirname (node:path:1276:5)
	at a (/home/leigh/.vscode/extensions/asyncapi.asyncapi-preview-0.4.0/dist/extension.js:1:179602)
	at /home/leigh/.vscode/extensions/asyncapi.asyncapi-preview-0.4.0/dist/extension.js:1:181584
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async s._executeContributedCommand (/snap/code/113/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:92:111367) asyncapi.preview {"value":"asyncapi.asyncapi-preview","_lower":"asyncapi.asyncapi-preview"}
```

Maybe the extension is unable to find an executable named `asyncapi`? Unsure how to proceed or how this should be sandboxed. Thanks for looking into this! :bowing_woman: 

- Schema: https://github.com/bitsy-ai/printnanny-asyncapi-schema/blob/main/2.5.0/printnanny-os.yml

#### Expected behavior
File preview opens in a new panel.

**Comment by derberg** [comment]
Works well with:
```yml
Version: 1.72.2
Commit: d045a5eda657f4d7b676dedbfa7aab8207f8a075
Date: 2022-10-12T22:16:30.254Z (1 mo ago)
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 20.6.0
Sandboxed: No
```


now I made an upgrade
```yml
Version: 1.73.1
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-09T02:08:38.961Z (3 wks ago)
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 20.6.0
Sandboxed: No
```

The only different that I can see between our setup os OS. I'm on Mac.

other extensions that support preview work for you? like markdown previewer for example?


and still works, both `command+shift+p` and also menu
<img width="200" alt="Screenshot 2022-12-01 at 12 47 53" src="https://user-images.githubusercontent.com/6995927/205045272-3d747935-b1a9-4cc9-a92d-0fe603908903.png">
