### ISSUE TITLE
Message binding version 0.3.0 produces empty screen

### ISSUE THREAD

**Issue by eshepelyuk** [asyncapi/vs-asyncapi-preview#214]
### Describe the bug.

Preivew doesn't render anything.

### Expected behavior

Proper AsyncAPI HTLM rendered.

### Screenshots

![image](https://github.com/asyncapi/vs-asyncapi-preview/assets/1279477/7057554d-d005-402b-a98c-bad2de0e2321)

### How to Reproduce

Create AsyncAPI document with following content
```yaml
asyncapi: 3.0.0
info:
  title: test
  version: 0.1.0
components:
  messages:
    myMessage:
      bindings:
        http:
          bindingVersion: 0.3.0
          statusCode: 202
```

### 🥦 Browser

None

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue ?

No, someone else can work on it
